### ISSUE TITLE
Suggestion: Generate a larger random (such as u128) and then byteshift downward to get multiple random characters.

### ISSUE THREAD

**Issue by GenerelSchwerz** [Sebbl0508/discord-nitro-generator#3]
'Ello there, I'm the author of https://github.com/nxg-org/c-nitro-gen-releases. :XD:

Sorry about some of my followers, you were part of the reason why I began my project so I compared myself to you. If they bothered you, you can let me know.

If you want to come talk to me about speeding your code up, you can hit me up at @Rocky#5000.

The main limiter of generators is how many times they have to call random. Bypass that and you're home free. Try to look into minimizing the amount of random calls you make.

**Comment by Sebbl0508** [comment]
Hey, thanks for writing, your discord (?) seems to invalid tho, i'll gladly write you there
